events {
    worker_connections 1024;
}

http {
    upstream auth {
        server auth-service:8001;
    }
    upstream account {
        server account-service:8002;
    }
    upstream fund {
        server fund-service:8003;
    }
    upstream portfolio {
        server portfolio-service:8004;
    }
    upstream trade {
        server trade-service:8005;
    }

    server {
        listen 80;

        location /api/auth/ {
            proxy_pass http://auth/;
        }
        location /api/account/ {
            proxy_pass http://account/;
        }
        location /api/fund/ {
            proxy_pass http://fund/;
        }
        location /api/portfolio/ {
            proxy_pass http://portfolio/;
        }
        location /api/trade/ {
            proxy_pass http://trade/;
        }
    }
}
